version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - infrastructure


  - package-ecosystem: "docker"
    directories:
      - /prometheus/
      - /grafana/
    schedule:
      interval: "monthly"
    labels:
      - infrastructure